# Generated by Django 3.2.18 on 2023-03-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230302_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Teacher'), (2, 'Student')], default=1, verbose_name='Статус пользователя'),
        ),
    ]
